### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by hmcy** [zither/opencq#1]
请问在什么版本的PHP和MySQL上运行最合适？可以增加网页后台功能吗？

**Comment by zither** [comment]
示例环境使用的是 PHP 7.4.3 和 MariaDB 10.3.22，本地环境使用的 PHP 8.0.1-dev 和 MariaDB-10.4.18，均可以正常运行。
你看开源协议就应该明白这个项目没有什么后续更新，现在只包含一个非常简单的后台管理功能。

**Comment by hmcy** [comment]
你现在是修复BUG吗？有没有接着开发下去的打算？

**Comment by zither** [comment]
不会修复BUG，不会继续开发。

**Comment by hmcy** [comment]
可以问一下入口文件是哪一个吗？或者说有安装教程吗？

**Comment by zither** [comment]
```
When I wrote this, only God and I understood what I was doing.
Now, only God knows.
```

![Good Luck](https://raw.githubusercontent.com/me-shaon/GLWTPL/master/good-luck.gif)
